Repository theseus-rs/rsql, pull requests merged in 2024-09, with the labels that each got.

#190 fix:rename exit in zh , duplicate with quit ,not unique
  rsql_core/locales/commands-exit.yml
Labels: fix

#191 build: update cargo-dist to 0.22
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
Labels: build

#192 chore: update postgresql_embedded and sqlx
  Cargo.lock
  Cargo.toml
Labels: internal
