Repository theseus-rs/rsql, pull requests merged in 2024-10, with the labels that each got.

#194 feat: update postgresql embedded to version 17
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  rsql_drivers/src/postgres/driver.rs
  rsql_drivers/src/postgresql/driver.rs
  rsql_drivers/src/sqlserver/driver.rs
  rsql_drivers/src/sqlserver/metadata.rs
  rust-toolchain.toml
Labels: enhancement

#196 refactor: specialized trait for toggle-able shell commands
  rsql_core/locales/commands-bail.yml
  rsql_core/locales/commands-changes.yml
  rsql_core/locales/commands-color.yml
  rsql_core/locales/commands-footer.yml
  rsql_core/locales/commands-header.yml
  rsql_core/locales/commands-rows.yml
  rsql_core/locales/commands-timer.yml
  rsql_core/src/commands/bail.rs
  rsql_core/src/commands/changes.rs
  rsql_core/src/commands/color.rs
  rsql_core/src/commands/command.rs
  rsql_core/src/commands/footer.rs
  rsql_core/src/commands/header.rs
  rsql_core/src/commands/mod.rs
  rsql_core/src/commands/rows.rs
  rsql_core/src/commands/timer.rs
Labels: internal

#197 test: update postgresql tests to use posgresql-embedded on all plattforms
  rsql_drivers/Cargo.toml
  rsql_drivers/src/postgres/driver.rs
  rsql_drivers/src/postgresql/driver.rs
Labels: internal

#195 build: update codecov action
  .github/workflows/checks.yml
  .github/workflows/ci.yml
Labels: build

#198 fix: revert sqlx from 0.8.2 to 0.7.4 to correct mysql and mariadb string conversion errors
  .github/workflows/checks.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  rsql_drivers/src/mariadb/driver.rs
  rsql_drivers/src/mysql/driver.rs
  rsql_drivers/src/mysql/metadata.rs
Labels: fix

#199 feat: add redshift driver
  .github/workflows/checks.yml
  README.md
  rsql_cli/Cargo.toml
  rsql_cli/docs/src/chapter1/first-query.md
  rsql_cli/docs/src/chapter2/bail/demo.cast
  rsql_cli/docs/src/chapter2/bail/demo.gif
  rsql_cli/docs/src/chapter2/changes/demo.cast
  rsql_cli/docs/src/chapter2/changes/demo.gif
  rsql_cli/docs/src/chapter2/clear/demo.cast
  rsql_cli/docs/src/chapter2/clear/demo.gif
  rsql_cli/docs/src/chapter2/color/demo.cast
  rsql_cli/docs/src/chapter2/color/demo.gif
  rsql_cli/docs/src/chapter2/demo.cast
  rsql_cli/docs/src/chapter2/demo.gif
  rsql_cli/docs/src/chapter2/describe/demo.cast
  rsql_cli/docs/src/chapter2/describe/demo.gif
  rsql_cli/docs/src/chapter2/drivers/demo.cast
  rsql_cli/docs/src/chapter2/drivers/demo.gif
  rsql_cli/docs/src/chapter2/drivers/index.md
  rsql_cli/docs/src/chapter2/exit/demo.cast
  rsql_cli/docs/src/chapter2/exit/demo.gif
  rsql_cli/docs/src/chapter2/footer/demo.cast
  rsql_cli/docs/src/chapter2/footer/demo.gif
  rsql_cli/docs/src/chapter2/format/demo.cast
  rsql_cli/docs/src/chapter2/format/demo.gif
  rsql_cli/docs/src/chapter2/header/demo.cast
  rsql_cli/docs/src/chapter2/header/demo.gif
  rsql_cli/docs/src/chapter2/help/demo.cast
  rsql_cli/docs/src/chapter2/indexes/demo.cast
  rsql_cli/docs/src/chapter2/indexes/demo.gif
  rsql_cli/docs/src/chapter2/limit/demo.cast
  rsql_cli/docs/src/chapter2/limit/demo.gif
  rsql_cli/docs/src/chapter2/locale/demo.cast
  rsql_cli/docs/src/chapter2/locale/demo.gif
  rsql_cli/docs/src/chapter2/print/demo.cast
  rsql_cli/docs/src/chapter2/print/demo.gif
  rsql_cli/docs/src/chapter2/quit/demo.cast
  rsql_cli/docs/src/chapter2/quit/demo.gif
  rsql_cli/docs/src/chapter2/rows/demo.cast
  rsql_cli/docs/src/chapter2/rows/demo.gif
  rsql_cli/docs/src/chapter2/schemas/demo.cast
  rsql_cli/docs/src/chapter2/schemas/demo.gif
  rsql_cli/docs/src/chapter2/sleep/demo.cast
  rsql_cli/docs/src/chapter2/sleep/demo.gif
  rsql_cli/docs/src/chapter2/system/demo.cast
  rsql_cli/docs/src/chapter2/tables/demo.cast
  rsql_cli/docs/src/chapter2/tables/demo.gif
  rsql_cli/docs/src/chapter2/timer/demo.cast
  rsql_cli/docs/src/chapter2/timer/demo.gif
  rsql_cli/resources/demo.cast
  rsql_cli/resources/demo.gif
  rsql_core/Cargo.toml
  rsql_core/src/commands/drivers.rs
  rsql_drivers/Cargo.toml
  rsql_drivers/src/driver.rs
  rsql_drivers/src/lib.rs
  rsql_drivers/src/redshift/driver.rs
  rsql_drivers/src/redshift/mod.rs
Labels: enhancement

#202 refactor!: remove unnecessary Row struct
  rsql_core/src/commands/describe.rs
  rsql_core/src/commands/indexes.rs
  rsql_core/src/commands/schemas.rs
  rsql_core/src/commands/tables.rs
  rsql_drivers/src/connection.rs
  rsql_drivers/src/duckdb/driver.rs
  rsql_drivers/src/duckdb/metadata.rs
  rsql_drivers/src/lib.rs
  rsql_drivers/src/libsql/driver.rs
  rsql_drivers/src/libsql/metadata.rs
  rsql_drivers/src/mysql/driver.rs
  rsql_drivers/src/mysql/metadata.rs
  rsql_drivers/src/postgres/driver.rs
  rsql_drivers/src/postgresql/driver.rs
  rsql_drivers/src/postgresql/metadata.rs
  rsql_drivers/src/row.rs
  rsql_drivers/src/rusqlite/driver.rs
  rsql_drivers/src/snowflake/driver.rs
  rsql_drivers/src/sqlite/driver.rs
  rsql_drivers/src/sqlite/metadata.rs
  rsql_drivers/src/sqlserver/driver.rs
  rsql_drivers/src/sqlserver/metadata.rs
  rsql_formatters/src/ascii.rs
  rsql_formatters/src/csv.rs
  rsql_formatters/src/delimited.rs
  rsql_formatters/src/expanded.rs
  rsql_formatters/src/footer.rs
  rsql_formatters/src/html.rs
  rsql_formatters/src/json.rs
  rsql_formatters/src/jsonl.rs
  rsql_formatters/src/markdown.rs
  rsql_formatters/src/plain.rs
  rsql_formatters/src/psql.rs
  rsql_formatters/src/sqlite.rs
  rsql_formatters/src/table.rs
  rsql_formatters/src/tsv.rs
  rsql_formatters/src/unicode.rs
  rsql_formatters/src/xml.rs
  rsql_formatters/src/yaml.rs
Labels: internal, breaking

#201 refactor!: remove public access for individual drivers
  README.md
  rsql_drivers/Cargo.toml
  rsql_drivers/src/lib.rs
Labels: internal, breaking

#203 refactor: add connection url
  rsql_drivers/src/connection.rs
  rsql_drivers/src/duckdb/driver.rs
  rsql_drivers/src/libsql/driver.rs
  rsql_drivers/src/mariadb/driver.rs
  rsql_drivers/src/mysql/driver.rs
  rsql_drivers/src/postgres/driver.rs
  rsql_drivers/src/postgresql/driver.rs
  rsql_drivers/src/redshift/driver.rs
  rsql_drivers/src/rusqlite/driver.rs
  rsql_drivers/src/snowflake/driver.rs
  rsql_drivers/src/sqlite/driver.rs
  rsql_drivers/src/sqlserver/driver.rs
  rsql_drivers/src/sqlserver/metadata.rs
Labels: internal

#193 feat: basic autocomplete of table names where metadata is available. …
  rsql_core/locales/commands-completions.yml
  rsql_core/src/commands/command.rs
  rsql_core/src/commands/completions.rs
  rsql_core/src/commands/mod.rs
  rsql_core/src/configuration.rs
  rsql_core/src/executors/executor.rs
  rsql_core/src/executors/sql.rs
  rsql_core/src/shell/completer.rs
  rsql_core/src/shell/helper.rs
  rsql_core/src/shell/repl.rs
  rsql_drivers/src/connection.rs
  rsql_drivers/src/driver.rs
  rsql_drivers/src/duckdb/driver.rs
  rsql_drivers/src/duckdb/metadata.rs
  rsql_drivers/src/libsql/metadata.rs
  rsql_drivers/src/metadata.rs
  rsql_drivers/src/mysql/driver.rs
  rsql_drivers/src/mysql/metadata.rs
  rsql_drivers/src/postgres/driver.rs
  rsql_drivers/src/postgresql/driver.rs
  rsql_drivers/src/postgresql/metadata.rs
  rsql_drivers/src/rusqlite/driver.rs
  rsql_drivers/src/snowflake/driver.rs
  rsql_drivers/src/sqlite/driver.rs
  rsql_drivers/src/sqlite/metadata.rs
  rsql_drivers/src/sqlserver/driver.rs
  rsql_drivers/src/sqlserver/metadata.rs
Labels: enhancement

#204 chore: update lint macros
  rsql_cli/src/main.rs
  rsql_core/src/commands/sleep.rs
  rsql_core/src/configuration.rs
  rsql_core/src/shell/completer.rs
  rsql_drivers/src/driver.rs
  rsql_drivers/src/duckdb/driver.rs
  rsql_drivers/src/lib.rs
  rsql_drivers/src/mariadb/driver.rs
  rsql_drivers/src/mysql/driver.rs
  rsql_drivers/src/mysql/metadata.rs
  rsql_drivers/src/postgresql/driver.rs
  rsql_drivers/src/rusqlite/driver.rs
  rsql_drivers/src/snowflake/driver.rs
  rsql_drivers/src/sqlserver/driver.rs
  rsql_drivers/src/value.rs
  rsql_formatters/src/formatter.rs
  rsql_formatters/src/lib.rs
Labels: internal

#218 build: update to Rust 1.82.0
  rust-toolchain.toml
Labels: build

#219 build: update to cargo-dist 0.23.0
  .github/workflows/release.yml
  Cargo.toml
  dist-workspace.toml
Labels: build
